// Generated by gencpp from file local_ssh/Feature.msg
// DO NOT EDIT!


#ifndef LOCAL_SSH_MESSAGE_FEATURE_H
#define LOCAL_SSH_MESSAGE_FEATURE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace local_ssh
{
template <class ContainerAllocator>
struct Feature_
{
  typedef Feature_<ContainerAllocator> Type;

  Feature_()
    : label()
    , x(0.0)
    , y(0.0)
    , yaw(0.0)
    , confidence(0.0)  {
    }
  Feature_(const ContainerAllocator& _alloc)
    : label(_alloc)
    , x(0.0)
    , y(0.0)
    , yaw(0.0)
    , confidence(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _label_type;
  _label_type label;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef float _confidence_type;
  _confidence_type confidence;




  typedef boost::shared_ptr< ::local_ssh::Feature_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::local_ssh::Feature_<ContainerAllocator> const> ConstPtr;

}; // struct Feature_

typedef ::local_ssh::Feature_<std::allocator<void> > Feature;

typedef boost::shared_ptr< ::local_ssh::Feature > FeaturePtr;
typedef boost::shared_ptr< ::local_ssh::Feature const> FeatureConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::local_ssh::Feature_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::local_ssh::Feature_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace local_ssh

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'local_ssh': ['/home/stumbo/catkin_ws/src/local_ssh/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::local_ssh::Feature_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::local_ssh::Feature_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::local_ssh::Feature_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::local_ssh::Feature_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::local_ssh::Feature_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::local_ssh::Feature_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::local_ssh::Feature_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0fdae69ea110b58c430c8fda60fdfd4f";
  }

  static const char* value(const ::local_ssh::Feature_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0fdae69ea110b58cULL;
  static const uint64_t static_value2 = 0x430c8fda60fdfd4fULL;
};

template<class ContainerAllocator>
struct DataType< ::local_ssh::Feature_<ContainerAllocator> >
{
  static const char* value()
  {
    return "local_ssh/Feature";
  }

  static const char* value(const ::local_ssh::Feature_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::local_ssh::Feature_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string label\n\
float32 x\n\
float32 y\n\
float32 yaw\n\
float32 confidence\n\
";
  }

  static const char* value(const ::local_ssh::Feature_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::local_ssh::Feature_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.label);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.yaw);
      stream.next(m.confidence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Feature_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::local_ssh::Feature_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::local_ssh::Feature_<ContainerAllocator>& v)
  {
    s << indent << "label: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.label);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOCAL_SSH_MESSAGE_FEATURE_H
