// Generated by gencpp from file px4_autonomy/Takeoff.msg
// DO NOT EDIT!


#ifndef PX4_AUTONOMY_MESSAGE_TAKEOFF_H
#define PX4_AUTONOMY_MESSAGE_TAKEOFF_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace px4_autonomy
{
template <class ContainerAllocator>
struct Takeoff_
{
  typedef Takeoff_<ContainerAllocator> Type;

  Takeoff_()
    : header()
    , take_off(0)  {
    }
  Takeoff_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , take_off(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _take_off_type;
  _take_off_type take_off;





  typedef boost::shared_ptr< ::px4_autonomy::Takeoff_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px4_autonomy::Takeoff_<ContainerAllocator> const> ConstPtr;

}; // struct Takeoff_

typedef ::px4_autonomy::Takeoff_<std::allocator<void> > Takeoff;

typedef boost::shared_ptr< ::px4_autonomy::Takeoff > TakeoffPtr;
typedef boost::shared_ptr< ::px4_autonomy::Takeoff const> TakeoffConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px4_autonomy::Takeoff_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px4_autonomy::Takeoff_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace px4_autonomy

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'px4_autonomy': ['/home/stumbo/catkin_ws/src/px4_autonomy/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::px4_autonomy::Takeoff_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_autonomy::Takeoff_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_autonomy::Takeoff_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_autonomy::Takeoff_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_autonomy::Takeoff_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_autonomy::Takeoff_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px4_autonomy::Takeoff_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ad8f4b260ba0267ba07ce4f218666235";
  }

  static const char* value(const ::px4_autonomy::Takeoff_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xad8f4b260ba0267bULL;
  static const uint64_t static_value2 = 0xa07ce4f218666235ULL;
};

template<class ContainerAllocator>
struct DataType< ::px4_autonomy::Takeoff_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px4_autonomy/Takeoff";
  }

  static const char* value(const ::px4_autonomy::Takeoff_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px4_autonomy::Takeoff_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint8 take_off\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::px4_autonomy::Takeoff_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px4_autonomy::Takeoff_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.take_off);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Takeoff_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px4_autonomy::Takeoff_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px4_autonomy::Takeoff_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "take_off: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.take_off);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX4_AUTONOMY_MESSAGE_TAKEOFF_H
